server:
  port: 8081

spring:
  profiles:
    include: datasource










mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





camunda:
  bpm:
    # 配置账户密码来访问Camunda自带的管理界面
    admin-user:
      id: admin
      password: admin
      first-name: admin
    filter:
      create: All tasks
    #指定数据库类型
    #    database:
    #      type: mysql
    #禁止自动部署resources下面的bpmn文件
    auto-deployment-enabled: false
#    #禁止index跳转到Camunda自带的管理界面，默认true
#    webapp:
#      index-redirect-enabled: true

