spring:
  datasource:
    dynamic:
      datasource:
        main:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mtf?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          password: mysql
          username: mysql

        second:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test18?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          password: mysql
          username: mysql

#        threed:
#          driver-class-name: oracle.jdbc.OracleDriver
#          url: jdbc:oracle:thin:@localhost:1521/orcl
#          password: LD_803_0602
#          username: LD_803_0602
      primary: main